import Head from 'next/head'
import { supabase } from "../utils/supabase"
import Link from 'next/link'

export default function Home({ lesson }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'w-full h-screen flex flex-col items-center justify-center'}>
       {lesson.map((data:any) => (
         <Link href={`/${data.id}`} key={data.id} className="border my-3 rounded-lg w-80 h-32 drop-shadow-md flex items-center justify-center hover:scale-105">
           <h1>{data.title}</h1>
         </Link>
       ))}
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const { data: lesson } = await supabase.from('lesson').select('*')

  return {
    props: {
      lesson,
    }
  }
}
